const data = [
    {
        id: 1,
        title: 'Comparison: Real versus AI',
        student: "Dimitri Meavilla",
        anchor: "projet1",
        real_picture: "real_picture_Dimitri.jpg",
        generate_picture: "generate_picture_Dimitri.png",
        description: "A photo of a hill filled with trees, with a Chinese-style palace building overlooking the hill.In the foreground, at the bottom of the photo, a stone fence borders the foot of the hill along with a Chinese temple-style cabin. The photo is taken at dusk, with a cloudy sky, and the orange rays of the sun reflecting on some of the clouds",
    },

    {
        id: 2,
        title: 'Political images',
        student: "Nicolas Caron",
        anchor: "lien",
        real_picture: "President_Barack_Obama.jpg",
        generate_picture: "obama_wc.png",
        description: "A pictures of Obama who's going on toilet.",
    },
    {
        id: 3,
        title: 'AI Fails',
        student: "Sami AMRI",
        anchor: "fail",
        real_picture: "ia-fail1.jpg",
        generate_picture: "ia-fail3.jpg",
        description: "AI was asked to transform the pictures into art",
    }, {
        id: 4,
        title: 'AI VS Professional pictures',
        student: "Noa David",
        anchor: "Pro",
        real_picture: "ia_picture.webp",
        generate_picture: "picture_noa.jpg",
        description: "hello... It's me",
    },
    {
        id: 5,
        title: 'Image modification by AI',
        student: "Corentin Cuyvers",
        anchor: "Modif",
        real_picture: "Mont-Jiuhua.jpeg",
        generate_picture: "Corentin_replace_the_temple_by_a_modern_building.png",
        description: "AI was asked to transform the image by replacing the old chinese building by a modern interpretation of it.",
    },
]